server:
  port: 30000
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
  sleuth:
    sampler:
      probability: 1
  #暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'