server:
  port: 25000

spring:
  #暴露所有端点
  zipkin:
    base-url: http://${ip_addr}:9411/
    discovery-client-enabled: false
    sender:
      type: web
  rabbitmq:
    host: ${ip_addr}
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
  session:
    store-type: redis
  thymeleaf:
    cache: false
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
        port: 8719
  sleuth:
    sampler:
      probability: 1


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0