server:
  port: 20000
spring:
  thymeleaf:
    cache: false
  session:
    store-type: redis
    timeout: 30m
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
  sleuth:
    sampler:
      probability: 1
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
